name: Mister F Learning
title: Mister F
description: Qualified teaching for 11-18 year olds in West Yorkshire and remotely.
host: 0.0.0.0

repository: cmbuckley/misterf.co.uk
url: https://misterf.co.uk
baseurl: ""

markdown: kramdown
highlighter: rouge

exclude:
  - CNAME
  - Gemfile

sass:
  style: compressed

social:
  instagram: misterflearning
  email: hello@misterf.co.uk
